# -- Site Configuration --

# URL to the root of your website.
baseURL = "https://comba92.github.io/"

# Site's language code
languageCode = 'en-us'

title = "Comba92's Site"

theme = "kayal"

# Number of articles per page in the listing.
[pagination]
  pagerSize = 6

# Enable processing of emojis in markdown.
enableEmoji = true

[markup]
  [markup.highlight]
    # https://xyproto.github.io/splash/docs/all.html
    style = 'evergarden'
    tabWidth = 2
    codeFences = true
    lineNos = true


# Enable creation of robots.txt for search engine crawling.
enableRobotsTXT = true

# Length of default summaries.
summaryLength = 0

# Build drafts during site generation.
buildDrafts = true
# Build pages with future dates during site generation.
buildFuture = true

# The types of outputs to generate for the homepage.
# RSS is required to create RSS feeds, and JSON is needed for the search to function.
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Sitemap setting
[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

# Google Analytics Configuration
# [services]
#   [services.googleAnalytics]
#     ID = 'G-MEASUREMENT_ID'

# Google Analytics Configuration
[services]
  [services.googleAnalytics]
    ID = 'G-9FX5VCRQV3'