# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, page, url, pre, weight.

# Add a trailing '/' to local URLs.
# For example: /posts/
# NOT: /posts

# `pre` is an icon ID. For a list of all available icons, check [https://github.com/mnjm/kayal/tree/main/assets/icons]

# [[main]]
# name = "posts"
# title = "Posts"
# url = "/posts/"
# weight = 1
#
# [[main]]
# name = "tags"
# title = "Tags"
# url = "/tags/"
# weight = 2
#
# [[main]]
# name = "about"
# title = "About"
# url = "/about/"
# weight = 3
#
# [[main]]
# name = "github"
# pre = "github"
# name = ""
# url = "https://github.com/mnjm/kayal"
# weight = 4

[[main]]
name = 'posts'
title = 'Posts'
url = '/posts/'
weight = 1

[[main]]
name = 'tags'
title = 'Tags'
url = '/tags/'
weight = 2

[[main]]
name = "github"
pre = "github"
url = "https://github.com/Comba92"
weight = 3

[[main]]
name = "twitter"
pre = "twitter"
url = "https://x.com/combaart"
weight = 4

[[main]]
name = "discord"
pre = "discord"
url = "discord"
weight = 5